### ISSUE TITLE
Attribution-Reporting-Eligible header not sent on Image() object

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/privacy-sandbox-dev-support#125]
The following not working on Canary. 

1. Enable Attribution Reporting by opening Settings, searching for Privacy, select Ad Privacy, then ensure Ad Measurement is toggled on. 
2. Open a tab and navigate to chrome://attribution-internals. It should display "Attribution Reporting is currently enabled in this browser." 
3. Navigate to https://www.google.com.
4. Open console and execute the following code:
`var img = new Image(); img.setAttribute('attributionsrc', 'https://www.google.com/gen_204'); img.src="https://www.google.com/gen_204";`

Expected behavior, `Attribution-Reporting-Enabled` request header sent and `attributionsrc` URL fetched. 
Works on Dev, Beta.

**Comment by maudnals** [comment]
Hi @dmdabbs, thank you for the detailed repro steps!
I couldn't reproduce this on Canary 117.0.5899.0⏤this may have been due to a bug in a former Canary version.
Can you still repro this issue?

**Comment by dmdabbs** [comment]
Hello @maudnals. I see the same behavior.

chrome://settings/help
`Version 117.0.5899.0 (Official Build) canary (64-bit)`

**Comment by maudnals** [comment]
Thanks @dmdabbs,
 
> Enable Attribution Reporting by opening Settings, searching for Privacy, select Ad Privacy, then ensure Ad Measurement is toggled on.

If I understand correctly, what you're turning on here are the **origin trial** features, i.e. if a site is intending to use Attribution Reporting, it will be able to.  

Can you try the following:
* Navigate to chrome://flags/#enable-experimental-web-platform-features
* **Enable**
* Restart your browser
* Retry the above ⏤ This should now work

Note:
* I agree that "Attribution Reporting is currently enabled in this browser." is misleading in this case!
* The API will be gradually enabled in Chrome Stable 115, and enrollment will be needed. Details here: https://groups.google.com/u/0/a/chromium.org/g/attribution-reporting-api-dev/c/w41-x4HmJO4

**Comment by dmdabbs** [comment]
Hello @maudnals.

I was about to document that it was still not working, but then canary reported a new version available. I updated to "Version 117.0.5901.0 (Official Build) canary (64-bit)" and I can see the expected results.

```
//
// fwiw, I updated the urls so that each is identifiable and the img.src is actually an image response
//
var img = new Image(); img.setAttribute('attributionsrc','https://www.google.com/gen_204?attributionsrc'); img.src="https://www.google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png";
```

Options Enabled:

- Privacy Sandbox Ads APIs
- Privacy Sandbox Settings V4


Observations:

1. As expected, it works _without_ turning on `enable-experimental-web-platform-features`
2. The headers are now 'GREASED', per [the recent PR](https://github.com/WICG/attribution-reporting-api/pull/824/commits/4882628448121602397f785ef730fba96afa8df2)

Caveat:

- It only works after I had run a google search or just clicking in the address bar and pressing Enter. It does not work simply opening a new tab to google.com  DevTools reports provisional headers and the attributionsrc is not issued. This is probably some weird corner case

Questions:

- How does one use the following option to force enrollment? If it is a command line flag what is the name? Appreciate any link to docs.  

```
Privacy Sandbox Enrollment Overrides
Allows a list of sites to use Privacy Sandbox features without them being enrolled and attested into the Privacy Sandbox experiment. 
See: https://developer.chrome.com/en/docs/privacy-sandbox/enroll/ – Mac, Windows, Linux, ChromeOS, Android, Fuchsia, Lacros
```

**Comment by dmdabbs** [comment]
Thank you, @maudnals. I saw that there was some bug in the UI preventing that flag input from working. It was fixed.

**Comment by samdutton** [comment]
Assuming this is now resolved, so closing.

@dmdabbs: Feel free to reopen this issue if necessary.
